import { Product } from "@/types"

export const products: Product[] = [
    {
        id: "1",
        name: "Stratus X1 Carbon",
        description: "Ultra-lightweight carbon fiber chassis with high-performance internals.",
        price: 1299.00,
        currency: "USD",
        category: "Laptops",
        image: "https://images.unsplash.com/photo-1517336714731-489689fd1ca4?auto=format&fit=crop&q=80&w=1000",
    },
    {
        id: "2",
        name: "Aeris Noise Cancelling",
        description: "Industry-leading noise cancellation with 40-hour battery life.",
        price: 349.00,
        currency: "USD",
        category: "Audio",
        image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&q=80&w=1000",
    },
    {
        id: "3",
        name: "Lumina 4K Display",
        description: "32-inch 4K HDR monitor with color accuracy for professionals.",
        price: 699.00,
        currency: "USD",
        category: "Monitors",
        image: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&q=80&w=1000",
    },
    {
        id: "4",
        name: "ErgoChair Pro",
        description: "Ergonomic mesh chair designed for 24/7 comfort and support.",
        price: 499.00,
        currency: "USD",
        category: "Furniture",
        image: "https://images.unsplash.com/photo-1505843490538-5133c6c7d0e1?auto=format&fit=crop&q=80&w=1000",
    },
    {
        id: "5",
        name: "Mechanical Keychron",
        description: "Wireless mechanical keyboard with hot-swappable switches.",
        price: 89.00,
        currency: "USD",
        category: "Peripherals",
        image: "https://images.unsplash.com/photo-1587829741301-dc798b91a603?auto=format&fit=crop&q=80&w=1000",
    },
    {
        id: "6",
        name: "Stratus Dock",
        description: "Thunderbolt 4 dock with dual 4K support and 100W charging.",
        price: 249.00,
        currency: "USD",
        category: "Accessories",
        image: "https://images.unsplash.com/photo-1527814050087-3793815479db?auto=format&fit=crop&q=80&w=1000",
    },
    {
        id: "7",
        name: "Nomad Backpack",
        description: "Water-resistant tech backpack with dedicated laptop compartment.",
        price: 149.00,
        currency: "USD",
        category: "Accessories",
        image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&q=80&w=1000",
    },
    {
        id: "8",
        name: "Sonic True Wireless",
        description: "Compact true wireless earbuds with active noise cancellation.",
        price: 129.00,
        currency: "USD",
        category: "Audio",
        image: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&q=80&w=1000",
    },
]
